---
- name: Installing EPEL release
  yum:
    name: epel-release
    state: present

- name: Installing NGINX as Load Balancer
  package:
    name: nginx
    state: present

- name: Setting systemd unit for NGINX
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Rendering NGINX configuration file
  template:
    dest: /etc/nginx/nginx.conf
    src: nginx.conf.j2
  register: state

- name: Reload NGINX configuration
  systemd:
    name: nginx
    state: reloaded
  when: state.changed
