---
  - name: Installing EPEL release
    yum:
      name: epel-release
      state: present

  - name: Installing NGINX as Load Balancer
    package:
      name: nginx
      state: present

  - name: Setting systemd unit for NGINX
    systemd:
      name: nginx
      enabled: yes
      state: started

  - name: Rendering NGINX configuration file
    template:
      dest: /etc/nginx/conf.d/default.conf
      src: default.conf.j2

  - name: Deploying Kubernetes certificates
    copy:
      dest: "/home/{{ ansible_user }}/{{ item }}"
      src: "./../certificate-authority/files/{{ item }}"
    with_items:
      - kubernetes.pem
      - kubernetes-key.pem

  - name: Reload NGINX configuration
    systemd:
      name: nginx
      state: reloaded
