---
  - name: Installing the Client Tools
    hosts: localhost
    roles:
      - client-tools  

  - name: Provisioning a CA and Generating TLS Certificates
    hosts: localhost
    roles:
      - certificate-authority

  - name: Distributing Client Certificates for Controllers
    hosts: controllers
    roles:
      - role: certificate-authority-deployer
        items:
          - "./../certificate-authority/files/ca.pem"
          - "./../certificate-authority/files/ca-key.pem"
          - "./../certificate-authority/files/kubernetes-key.pem"
          - "./../certificate-authority/files/kubernetes.pem"

  - name: Distributing Client Certificates for Workers
    hosts: workers
    roles:
      - role: certificate-authority-deployer
        items:
          - "./../certificate-authority/files/ca.pem"
          - "./../certificate-authority/files/{{ ansible_nodename }}-key.pem"
          - "./../certificate-authority/files/{{ ansible_nodename }}.pem"
