---
  - name: Installing the Client Tools
    hosts: localhost
    roles:
      - client-tools  

  - name: Nodes bootstrap
    hosts: all
    roles:
      - nodes-bootstap

  - name: Provisioning a CA and Generating TLS Certificates
    hosts: localhost
    roles:
      - certificate-authority

  - name: Distributing Client Certificates for Controllers
    hosts: controllers
    roles:
      - role: certificate-authority-deployer
        items:
          - "./../certificate-authority/files/ca.pem"
          - "./../certificate-authority/files/ca-key.pem"
          - "./../certificate-authority/files/kubernetes-key.pem"
          - "./../certificate-authority/files/kubernetes.pem"

  - name: Distributing Client Certificates for Workers
    hosts: workers
    roles:
      - role: certificate-authority-deployer
        items:
          - "./../certificate-authority/files/ca.pem"
          - "./../certificate-authority/files/{{ ansible_nodename }}-key.pem"
          - "./../certificate-authority/files/{{ ansible_nodename }}.pem"

  - name: Kubernetes Configuration Files for Authentication
    hosts: localhost
    roles:
      - role: authentication-configs
        crt_path: "./../certificate-authority/files"

  - name: Distributing the Kubernetes Configuration Files
    hosts: workers
    roles:
      - authentication-configs-deployer

  - name: Generating the Data Encryption Config and Key
    hosts: localhost
    roles:
      - data-encryption

  - name: Distributing the Data Encryption Config and Key
    hosts: controllers
    roles:
      - data-encryption-deployer

  - name: Bootstrapping the etcd Cluster
    hosts: controllers
    roles:
      - etcd

  - name: Installing Kubernetes control plane
    hosts: controllers
    roles:
      - kube-control-plane

  - name: RBAC for Kubelet Authorization
    hosts: controllers[0]
    roles:
      - kube-control-plane-kubelet-rbac-auth

  - name: Opening firewall port for Controllers
    hosts: controllers
    roles:
      - lb-controllers-firewall

  - name: Installing Kubernetes API load balancer
    hosts: lb
    roles:
      - lb
