all:
  children:
    lb:
      become: true
      hosts:
        nginx:
          ansible_host: 10.240.0.125
          private_ip: 10.240.0.125
          public_ip: 10.240.0.125
          ansible_user: vagrant
          ansible_ssh_private_key_file: ./.vagrant/machines/lb/virtualbox/private_key
    controllers:
      hosts:
        controller-1:
          ansible_host: 10.240.0.11
          private_ip: 10.240.0.11
          ansible_user: vagrant
          ansible_ssh_private_key_file: ./.vagrant/machines/controller-1/virtualbox/private_key
        controller-2:
          ansible_host: 10.240.0.12
          private_ip: 10.240.0.12
          ansible_user: vagrant
          ansible_ssh_private_key_file: ./.vagrant/machines/controller-2/virtualbox/private_key
        controller-3:
          ansible_host: 10.240.0.13
          private_ip: 10.240.0.13
          ansible_user: vagrant
          ansible_ssh_private_key_file: ./.vagrant/machines/controller-3/virtualbox/private_key
    workers:
      hosts:
        worker-1:
          ansible_host: 10.240.0.21
          private_ip: 10.240.0.21
          ansible_user: vagrant
          ansible_ssh_private_key_file: ./.vagrant/machines/worker-1/virtualbox/private_key
        worker-2:
          ansible_host: 10.240.0.22
          private_ip: 10.240.0.22
          ansible_user: vagrant
          ansible_ssh_private_key_file: ./.vagrant/machines/worker-2/virtualbox/private_key
