---
  - set_fact:
      crt_path: "{{ role_path }}/files"

  - name: Gathering the CA configuration file
    template:
      src: ca-csr.json.j2
      dest: "{{ crt_path }}/ca-csr.json"

  - name: Create the CA certificate signing request
    shell: |
      cfssl gencert -initca {{ crt_path }}/ca-csr.json |
      cfssljson -bare {{ crt_path }}/ca

  - name: Gathering the Admin Client Certificate configuration file
    template:
      src: admin-csr.json.j2
      dest: "{{ crt_path }}/admin-csr.json"

  - name: Generate the `admin` client certificate and private key
    shell: |
      cfssl gencert \
        -ca={{ crt_path }}/ca.pem \
        -ca-key={{ crt_path }}/ca-key.pem \
        -config={{ crt_path }}/ca-config.json \
        -profile=kubernetes \
        {{ crt_path }}/admin-csr.json |
      cfssljson -bare {{ crt_path }}/admin

  - name: Gathering worker Kubelet configuration file
    template:
      src: worker-csr.json.j2
      dest: "{{ crt_path }}/{{ item }}-csr.json"
    with_items:
        - "{{ groups.workers }}"

  - name: "Generate the workers client certificate and private key"
    shell: |
      cfssl gencert \
        -ca={{ crt_path }}/ca.pem \
        -ca-key={{ crt_path }}/ca-key.pem \
        -config={{ crt_path }}/ca-config.json \
        -profile=kubernetes \
        -hostname={{ item }},{{ hostvars[item]['ansible_host'] }},{{ hostvars[item]['inventory_hostname'] }} \
        {{ crt_path }}/{{ item }}-csr.json |
      cfssljson -bare {{ crt_path }}/{{ item }}
    with_items:
      - "{{ groups.workers }}"
  
  - name: Gathering the kube-proxy Client Certificate configuration file
    template:
      src: kube-proxy-csr.json.j2
      dest: "{{ crt_path }}/kube-proxy-csr.json"
  
  - name: Generate the `kube-proxy` client certificate and private key
    shell: |
      cfssl gencert \
        -ca={{ crt_path }}/ca.pem \
        -ca-key={{ crt_path }}/ca-key.pem \
        -config={{ crt_path }}/ca-config.json \
        -profile=kubernetes \
        {{ crt_path }}/kube-proxy-csr.json |
      cfssljson -bare {{ crt_path }}/kube-proxy

  
  - name: Gathering the Kubernetes API Server Certificate configuration file
    template:
      src: kubernetes-csr.json.j2
      dest: "{{ crt_path }}/kubernetes-csr.json"
    
  - name: Generate the `kube-api` client certificate and private key
    shell: |
      cfssl gencert \
        -ca={{ crt_path }}/ca.pem \
        -ca-key={{ crt_path }}/ca-key.pem \
        -config={{ crt_path }}/ca-config.json \
        -hostname=10.32.0.1,{% for host in groups['controllers'] %}{{ hostvars[host]['ansible_host'] }},{{ hostvars[host]['inventory_hostname'] }},{% endfor %}127.0.0.1,kubernetes.default \
        -profile=kubernetes \
        {{ crt_path }}/kubernetes-csr.json |
      cfssljson -bare {{ crt_path }}/kubernetes
  