---
- set_fact:
    etcd_version: etcd-v3.2.11-linux-amd64
- set_fact:
    etcd_url: "https://github.com/coreos/etcd/releases/download/v3.2.11/{{ etcd_version }}.tar.gz"

- name: Download from GitHub
  uri:
    url: "{{ etcd_url }}"
    dest: "/tmp/{{ etcd_version }}.tar.gz"
    force: yes
    status_code: 200,304

- name: Creating required folders
  become: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
  - /etc/etcd
  - /var/lib/etcd

- name: Extracting from archive
  unarchive:
    remote_src: yes
    src: "/tmp/{{ etcd_version }}.tar.gz"
    dest: /tmp/

- name: Moving binaries
  become: yes
  copy:
    remote_src: yes
    src: /tmp/{{ etcd_version }}/{{ item }}
    dest: /usr/local/bin/
    mode: +x
  with_items:
  - etcd
  - etcdctl

- name: Copying certs
  become: yes
  copy:
    remote_src: yes
    src: "/home/{{ ansible_user }}/{{ item }}"
    dest: "/etc/etcd/{{ item }}"
  with_items:
  - ca.pem
  - kubernetes-key.pem
  - kubernetes.pem

- name: Deploying systemd.unit file
  become: yes
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  register: unit

- name: Starting `etcd` service
  become: yes
  systemd:
    daemon_reload: yes
    name: etcd.service
    enabled: yes
    state: "{{ 'restarted' if unit.changed else 'started' }}"

- name: Checking that `etcd` started
  shell: |
    ETCDCTL_API=3 etcdctl member list
  register: etcd_member_list
  until: etcd_member_list.rc == 0
  retries: 10
  delay: 1
  ignore_errors: yes
