---
  - name: Gathering Cluster Role YAML configuration
    template:
      src: ClusterRole.yml.j2
      dest: /tmp/ClusterRole.yml

  - name: Applying Cluste Role
    shell: |
      kubectl apply -f /tmp/ClusterRole.yml

  - name: Gathering Cluster Role Binding YAML configuration
    template:
      src: ClusterRoleBinding.yml.j2
      dest: /tmp/ClusterRoleBinding.yml

  - name: Applying Cluste Role Binding
    shell: |
      kubectl apply -f /tmp/ClusterRoleBinding.yml
